# Generated by Django 4.2.3 on 2023-07-12 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movieapp', '0002_alter_movie_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='img',
            field=models.ImageField(default='fgr', upload_to='gallery'),
            preserve_default=False,
        ),
    ]
