# Generated by Django 4.2.3 on 2023-07-21 05:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movieapp', '0003_movie_img'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='movie',
            new_name='Movie1',
        ),
    ]
